name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Explicitly install Docker (if necessary)
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      # Run the Playwright tests inside the Docker container
      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -v $(pwd)/playwright-report:/usr/src/app/playwright-report \
            playwright-tests

      # Upload Playwright report as artifact
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
